import { basicRateLimit } from "./server/middleware/rateLimit.js";
import { errorHandler } from "./server/middleware/errorHandler.js";
import express from "express";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import { healthRouter } from "./server/routes/health.js";
import { securityRouter } from "./server/routes/security.js";
import { securityHeaders, apiRateLimit } from "./server/lib/security.js";
import { authRouter } from "./server/modules/auth/routes.js";
import { projectRouter } from "./server/modules/projects/routes.js";
import { tiktokRouter } from "./server/modules/tiktok/routes.js";
import { videoRouter } from "./server/modules/video/routes.js";
import { growthRouter } from "./server/modules/growth/routes.js";
import { osRouter } from "./server/modules/os/routes.js";
import { cmoRouter } from "./server/modules/cmo/routes.js";
import { connectorsRouter } from "./server/modules/connectors/routes.js";
import { agentsRouter } from "./server/modules/agents/routes.js";
import { unifiedBrainRouter } from "./server/modules/unifiedBrain/routes.js";
import { executionRouter } from "./server/modules/execution/routes.js";
import { memoryRouter } from "./server/modules/memory/routes.js";
import { optimizationRouter } from "./server/modules/optimization/routes.js";
import { opportunitiesRouter } from "./server/modules/opportunities/routes.js";
import { webhooksRouter } from "./server/routes/webhooks.js";
import { trendsRouter } from "./server/modules/trends/routes.js";
import { leadsRouter } from "./server/modules/leads/routes.js";
import { billingRouter } from "./server/modules/billing/routes.js";
import { usageRouter } from "./server/modules/usage/routes.js";
import { emailsRouter } from "./server/modules/emails/routes.js";
import { betaRouter } from "./server/modules/beta/routes.js";
import { autoCampaignRouter } from "./server/modules/autocampaign/routes.js";
import { adminRouter } from "./server/modules/admin/routes.js";
import { metaRouter } from "./server/modules/meta/routes.js";
import { contentRouter } from "./server/modules/content/routes.js";
import { waitlistRouter } from "./server/modules/waitlist/routes.js";
import { analyticsRouter } from "./server/modules/analytics/routes.js";
import { onboardingRouter } from "./server/modules/onboarding/routes.js";
import { nichesRouter } from "./server/modules/niches/routes.js";
import { brainRouter } from "./server/modules/brain/routes.js";
import { creativeRouter } from "./server/modules/creative/routes.js";
dotenv.config();
const app = express();

app.use(basicRateLimit(180,60000));
app.use(securityHeaders);
app.use("/api", apiRateLimit(120, 60_000));
app.use(express.json({ limit: "1mb" }));
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
app.use(express.static(path.join(__dirname, "public")));

app.get("/landing", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "landing.html"));
});

app.get("/reset-password", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "reset-password.html"));
});
app.use("/api/health", healthRouter);
app.use("/api/security", securityRouter);
app.use("/api/auth", authRouter);
app.use("/api/projects", projectRouter);
app.use("/api/tiktok", tiktokRouter);
app.use("/api/video", videoRouter);
app.use("/api/growth", growthRouter);
app.use("/api/os", osRouter);
app.use("/api/cmo", cmoRouter);
app.use("/api/agents", agentsRouter);
app.use("/api/brain/unified", unifiedBrainRouter);
app.use("/api/execution", executionRouter);
app.use("/api/memory", memoryRouter);
app.use("/api/optimization", optimizationRouter);
app.use("/api/opportunities", opportunitiesRouter);
app.use("/api/connectors", connectorsRouter);
app.use("/api/webhooks", webhooksRouter);
app.use("/api/trends", trendsRouter);
app.use("/api/leads", leadsRouter);
app.use("/api/billing", billingRouter);
app.use("/api/usage", usageRouter);
app.use("/api/emails", emailsRouter);
app.use("/api/beta", betaRouter);
app.use("/api/autocampaign", autoCampaignRouter);
app.use("/api/admin", adminRouter);
app.use("/api/meta", metaRouter);
app.use("/api/content", contentRouter);
app.use("/api/waitlist", waitlistRouter);
app.use("/api/analytics", analyticsRouter);
app.use("/api/onboarding", onboardingRouter);
app.use("/api/niches", nichesRouter);
app.use("/api/brain", brainRouter);
app.use("/api/creative", creativeRouter);
app.get("*", (req, res) => res.sendFile(path.join(__dirname, "public", "index.html")));
export default app;

app.use(errorHandler);
