import express from "express";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import { healthRouter } from "./server/routes/health.js";
import { securityRouter } from "./server/routes/security.js";
import { securityHeaders, apiRateLimit } from "./server/lib/security.js";
import { authRouter } from "./server/modules/auth/routes.js";
import { projectRouter } from "./server/modules/projects/routes.js";
import { tiktokRouter } from "./server/modules/tiktok/routes.js";
import { videoRouter } from "./server/modules/video/routes.js";
import { trendsRouter } from "./server/modules/trends/routes.js";
import { leadsRouter } from "./server/modules/leads/routes.js";
import { billingRouter } from "./server/modules/billing/routes.js";
import { autoCampaignRouter } from "./server/modules/autocampaign/routes.js";
import { adminRouter } from "./server/modules/admin/routes.js";
import { metaRouter } from "./server/modules/meta/routes.js";
import { contentRouter } from "./server/modules/content/routes.js";
import { waitlistRouter } from "./server/modules/waitlist/routes.js";
import { analyticsRouter } from "./server/modules/analytics/routes.js";
import { onboardingRouter } from "./server/modules/onboarding/routes.js";
import { nichesRouter } from "./server/modules/niches/routes.js";
dotenv.config();
const app = express();
app.use(securityHeaders);
app.use("/api", apiRateLimit(120, 60_000));
app.use(express.json({ limit: "1mb" }));
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
app.use(express.static(path.join(__dirname, "public")));

app.get("/landing", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "landing.html"));
});

app.get("/reset-password", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "reset-password.html"));
});
app.use("/api/health", healthRouter);
app.use("/api/security", securityRouter);
app.use("/api/auth", authRouter);
app.use("/api/projects", projectRouter);
app.use("/api/tiktok", tiktokRouter);
app.use("/api/video", videoRouter);
app.use("/api/trends", trendsRouter);
app.use("/api/leads", leadsRouter);
app.use("/api/billing", billingRouter);
app.use("/api/autocampaign", autoCampaignRouter);
app.use("/api/admin", adminRouter);
app.use("/api/meta", metaRouter);
app.use("/api/content", contentRouter);
app.use("/api/waitlist", waitlistRouter);
app.use("/api/analytics", analyticsRouter);
app.use("/api/onboarding", onboardingRouter);
app.use("/api/niches", nichesRouter);
app.get("*", (req, res) => res.sendFile(path.join(__dirname, "public", "index.html")));
export default app;
